"""initial schema

Revision ID: 98d01594b2a6
Revises: 
Create Date: 2026-01-01 02:08:22.487627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d01594b2a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_share_links_attachment_id'), 'attachment_share_links', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_attachment_share_links_expires_at'), 'attachment_share_links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_attachment_share_links_id'), 'attachment_share_links', ['id'], unique=False)
    op.create_index(op.f('ix_attachment_share_links_token_hash'), 'attachment_share_links', ['token_hash'], unique=True)
    op.create_table('errand_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errand_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_errand_attachments_errand_id'), 'errand_attachments', ['errand_id'], unique=False)
    op.create_index(op.f('ix_errand_attachments_id'), 'errand_attachments', ['id'], unique=False)
    op.create_table('errands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('sensitivity', sa.String(), nullable=True),
    sa.Column('confirmation_sent_at', sa.Integer(), nullable=True),
    sa.Column('issue_reason', sa.String(), nullable=True),
    sa.Column('issue_notes', sa.String(), nullable=True),
    sa.Column('issue_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_preferred_resolution', sa.String(), nullable=True),
    sa.Column('issue_status', sa.String(), nullable=True),
    sa.Column('issue_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_resolution_notes', sa.String(), nullable=True),
    sa.Column('issue_evidence_attachment_ids', sa.String(), nullable=True),
    sa.Column('pickup_location', sa.String(), nullable=True),
    sa.Column('dropoff_location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errands_id'), 'errands', ['id'], unique=False)
    op.create_index(op.f('ix_errands_reference_number'), 'errands', ['reference_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_otp_hash', sa.String(), nullable=True),
    sa.Column('email_otp_expires_at', sa.Integer(), nullable=True),
    sa.Column('email_otp_last_sent_at', sa.Integer(), nullable=True),
    sa.Column('email_otp_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_verification_method', sa.String(), nullable=True),
    sa.Column('id_verification_status', sa.String(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('address_verification_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_errands_reference_number'), table_name='errands')
    op.drop_index(op.f('ix_errands_id'), table_name='errands')
    op.drop_table('errands')
    op.drop_index(op.f('ix_errand_attachments_id'), table_name='errand_attachments')
    op.drop_index(op.f('ix_errand_attachments_errand_id'), table_name='errand_attachments')
    op.drop_table('errand_attachments')
    op.drop_index(op.f('ix_attachment_share_links_token_hash'), table_name='attachment_share_links')
    op.drop_index(op.f('ix_attachment_share_links_id'), table_name='attachment_share_links')
    op.drop_index(op.f('ix_attachment_share_links_expires_at'), table_name='attachment_share_links')
    op.drop_index(op.f('ix_attachment_share_links_attachment_id'), table_name='attachment_share_links')
    op.drop_table('attachment_share_links')
    # ### end Alembic commands ###
