"""Add missing columns

Revision ID: c55798d8ed6a
Revises: 019_add_user_uuid
Create Date: 2026-09-07 21:28:02.815843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c55798d8ed6a'
down_revision: Union[str, Sequence[str], None] = '019_add_user_uuid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_visits_id'), 'analytics_visits', ['id'], unique=False)
    op.create_table('voice_call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errand_id', sa.Integer(), nullable=False),
    sa.Column('initiator_user_id', sa.Integer(), nullable=False),
    sa.Column('pilot_user_id', sa.Integer(), nullable=True),
    sa.Column('customer_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('conference_name', sa.String(), nullable=False),
    sa.Column('pilot_phone_mask', sa.String(), nullable=True),
    sa.Column('customer_phone_mask', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_call_sessions_conference_name'), 'voice_call_sessions', ['conference_name'], unique=True)
    op.create_index(op.f('ix_voice_call_sessions_errand_id'), 'voice_call_sessions', ['errand_id'], unique=False)
    op.create_index(op.f('ix_voice_call_sessions_id'), 'voice_call_sessions', ['id'], unique=False)
    op.create_table('errand_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errand_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['errand_id'], ['errands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errand_events_errand_id'), 'errand_events', ['errand_id'], unique=False)
    op.create_index(op.f('ix_errand_events_id'), 'errand_events', ['id'], unique=False)
    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errand_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['errand_id'], ['errands.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_errand_id'), 'incident_reports', ['errand_id'], unique=False)
    op.create_index(op.f('ix_incident_reports_id'), 'incident_reports', ['id'], unique=False)
    op.create_index(op.f('ix_incident_reports_pilot_id'), 'incident_reports', ['pilot_id'], unique=False)
    op.create_table('pilot_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_pilot_documents_id'), 'pilot_documents', ['id'], unique=False)
    op.create_index(op.f('ix_pilot_documents_pilot_id'), 'pilot_documents', ['pilot_id'], unique=False)
    op.create_table('support_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('handoff_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_conversations_id'), 'support_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_support_conversations_session_id'), 'support_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_support_conversations_user_id'), 'support_conversations', ['user_id'], unique=False)
    op.create_table('voice_call_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['voice_call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_call_events_id'), 'voice_call_events', ['id'], unique=False)
    op.create_index(op.f('ix_voice_call_events_session_id'), 'voice_call_events', ['session_id'], unique=False)
    op.create_table('incident_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_messages_id'), 'incident_messages', ['id'], unique=False)
    op.create_index(op.f('ix_incident_messages_incident_id'), 'incident_messages', ['incident_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_conversation_id'), 'support_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_support_messages_id'), 'support_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_errand_messages_created_at'), table_name='errand_messages')
    op.create_index(op.f('ix_errand_messages_id'), 'errand_messages', ['id'], unique=False)
    op.add_column('errands', sa.Column('pickup_contact_name', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('pickup_contact_phone', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('dropoff_contact_name', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('dropoff_contact_phone', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('errands', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('errands', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('errands', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('reviewer_rating', sa.Integer(), nullable=True))
    op.add_column('errands', sa.Column('reviewer_notes', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('review_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('errands', sa.Column('pickup_time_slot_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('errands', sa.Column('pickup_time_slot_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('errands', sa.Column('pickup_time_slot_date', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('pilot_id', sa.Integer(), nullable=True))
    op.add_column('errands', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('errands', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('errands', sa.Column('delivery_time', sa.Float(), nullable=True))
    op.add_column('errands', sa.Column('tracking_paused', sa.Boolean(), nullable=True))
    op.add_column('errands', sa.Column('signature_url', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('completion_notes', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('pilot_notes', sa.String(), nullable=True))
    op.add_column('errands', sa.Column('tip', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_errands_tip_paid_at'), table_name='errands')
    op.drop_index(op.f('ix_errands_tip_stripe_session_id'), table_name='errands')
    op.create_index(op.f('ix_errands_assigned_to'), 'errands', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_errands_pilot_id'), 'errands', ['pilot_id'], unique=False)
    op.drop_column('errands', 'payment_currency')
    op.drop_column('errands', 'payment_amount_total_minor')
    op.drop_column('errands', 'payment_amount_ngn_major')
    op.create_index(op.f('ix_pilot_employment_applications_id'), 'pilot_employment_applications', ['id'], unique=False)
    op.create_index(op.f('ix_pilot_employment_attachments_id'), 'pilot_employment_attachments', ['id'], unique=False)
    op.alter_column('pilot_locations', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('pilot_locations', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('pilot_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pilot_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pilot_locations_created_at'), table_name='pilot_locations')
    op.drop_index(op.f('idx_pilot_locations_errand_id'), table_name='pilot_locations')
    op.drop_index(op.f('idx_pilot_locations_pilot_id'), table_name='pilot_locations')
    op.create_index('idx_pilot_locations_pilot_created', 'pilot_locations', ['pilot_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pilot_locations_errand_id'), 'pilot_locations', ['errand_id'], unique=False)
    op.create_index(op.f('ix_pilot_locations_id'), 'pilot_locations', ['id'], unique=False)
    op.create_index(op.f('ix_pilot_locations_pilot_id'), 'pilot_locations', ['pilot_id'], unique=False)
    op.create_index(op.f('ix_promo_codes_id'), 'promo_codes', ['id'], unique=False)
    op.drop_constraint(op.f('uq_stripe_checkout_sessions_stripe_session_id'), 'stripe_checkout_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_stripe_checkout_sessions_stripe_session_id'), 'stripe_checkout_sessions', ['stripe_session_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_promo_codes_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_pilot_locations_pilot_id'), table_name='pilot_locations')
    op.drop_index(op.f('ix_pilot_locations_id'), table_name='pilot_locations')
    op.drop_index(op.f('ix_pilot_locations_errand_id'), table_name='pilot_locations')
    op.drop_index('idx_pilot_locations_pilot_created', table_name='pilot_locations')
    op.create_index(op.f('idx_pilot_locations_pilot_id'), 'pilot_locations', ['pilot_id'], unique=False)
    op.create_index(op.f('idx_pilot_locations_errand_id'), 'pilot_locations', ['errand_id'], unique=False)
    op.create_index(op.f('idx_pilot_locations_created_at'), 'pilot_locations', ['created_at'], unique=False)
    op.alter_column('pilot_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pilot_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pilot_locations', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=11, scale=8),
               existing_nullable=False)
    op.alter_column('pilot_locations', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=False)
    op.drop_index(op.f('ix_pilot_employment_attachments_id'), table_name='pilot_employment_attachments')
    op.drop_index(op.f('ix_pilot_employment_applications_id'), table_name='pilot_employment_applications')
    op.add_column('errands', sa.Column('payment_amount_ngn_major', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('errands', sa.Column('payment_amount_total_minor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('errands', sa.Column('payment_currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_errands_pilot_id'), table_name='errands')
    op.drop_index(op.f('ix_errands_assigned_to'), table_name='errands')
    op.create_index(op.f('ix_errands_tip_stripe_session_id'), 'errands', ['tip_stripe_session_id'], unique=False)
    op.create_index(op.f('ix_errands_tip_paid_at'), 'errands', ['tip_paid_at'], unique=False)
    op.drop_column('errands', 'tip')
    op.drop_column('errands', 'pilot_notes')
    op.drop_column('errands', 'completion_notes')
    op.drop_column('errands', 'photo_url')
    op.drop_column('errands', 'signature_url')
    op.drop_column('errands', 'tracking_paused')
    op.drop_column('errands', 'delivery_time')
    op.drop_column('errands', 'completed_at')
    op.drop_column('errands', 'started_at')
    op.drop_column('errands', 'pilot_id')
    op.drop_column('errands', 'pickup_time_slot_date')
    op.drop_column('errands', 'pickup_time_slot_end')
    op.drop_column('errands', 'pickup_time_slot_start')
    op.drop_column('errands', 'review_completed_at')
    op.drop_column('errands', 'reviewer_notes')
    op.drop_column('errands', 'reviewer_rating')
    op.drop_column('errands', 'review_status')
    op.drop_column('errands', 'assigned_at')
    op.drop_column('errands', 'assigned_to')
    op.drop_column('errands', 'updated_at')
    op.drop_column('errands', 'dropoff_contact_phone')
    op.drop_column('errands', 'dropoff_contact_name')
    op.drop_column('errands', 'pickup_contact_phone')
    op.drop_column('errands', 'pickup_contact_name')
    op.drop_index(op.f('ix_errand_messages_id'), table_name='errand_messages')
    op.create_index(op.f('ix_errand_messages_created_at'), 'errand_messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_support_messages_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_conversation_id'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_incident_messages_incident_id'), table_name='incident_messages')
    op.drop_index(op.f('ix_incident_messages_id'), table_name='incident_messages')
    op.drop_table('incident_messages')
    op.drop_index(op.f('ix_voice_call_events_session_id'), table_name='voice_call_events')
    op.drop_index(op.f('ix_voice_call_events_id'), table_name='voice_call_events')
    op.drop_table('voice_call_events')
    op.drop_index(op.f('ix_support_conversations_user_id'), table_name='support_conversations')
    op.drop_index(op.f('ix_support_conversations_session_id'), table_name='support_conversations')
    op.drop_index(op.f('ix_support_conversations_id'), table_name='support_conversations')
    op.drop_table('support_conversations')
    op.drop_index(op.f('ix_pilot_documents_pilot_id'), table_name='pilot_documents')
    op.drop_index(op.f('ix_pilot_documents_id'), table_name='pilot_documents')
    op.drop_table('pilot_documents')
    op.drop_index(op.f('ix_incident_reports_pilot_id'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_id'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_errand_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_errand_events_id'), table_name='errand_events')
    op.drop_index(op.f('ix_errand_events_errand_id'), table_name='errand_events')
    op.drop_table('errand_events')
    op.drop_index(op.f('ix_voice_call_sessions_id'), table_name='voice_call_sessions')
    op.drop_index(op.f('ix_voice_call_sessions_errand_id'), table_name='voice_call_sessions')
    op.drop_index(op.f('ix_voice_call_sessions_conference_name'), table_name='voice_call_sessions')
    op.drop_table('voice_call_sessions')
    op.drop_index(op.f('ix_analytics_visits_id'), table_name='analytics_visits')
    op.drop_table('analytics_visits')
    # ### end Alembic commands ###
