"""ErrandBridge Data Transfer Objects (DTO) Package."""

from app.dto.common import (
    CamelModel,
    FlexibleId,
    ErrandStatus,
    PilotAvailabilityStatus,
    UserRole,
    IncidentStatus,
    VerificationStatus,
    PaymentStatus,
    TrackingStatus,
    ResponseStatus,
    Money,
    PaginationMeta,
    PaginatedResponse,
    ApiError,
    ApiResponse,
)
from app.dto.pilot import (
    AvailableJobItem,
    PilotAvailableJobsResponse,
    PilotJobItem,
    PilotJobsResponse,
    PilotJobActionResponse,
    StartDeliveryResponse,
    CompleteDeliveryResponse,
    DelayReasonResponse,
    TrackingControlResponse,
    ActiveDeliveryResponse,
    PilotDocumentItem,
    PilotDocumentsListResponse,
    PilotStatsResponse,
    PilotAvailabilityResponse,
    PilotProfileResponse,
    PilotProfileUpdateResponse,
    PilotChangePasswordResponse,
)
from app.dto.tracking import TrackingStatusResponse
from app.dto.support import (
    IncidentReportItem,
    IncidentReportResponse,
    IncidentListResponse,
    IncidentMessageItem,
    IncidentMessagesListResponse,
    SupportConversationItem,
    SupportConversationsListResponse,
    SupportMessageItem,
    SupportMessagesListResponse,
    SupportActionResponse,
    IncidentAlertItem,
    IncidentAlertsResponse,
    IncidentResolveResponse,
    SupportHandoffAlertItem,
    SupportHandoffAlertsResponse,
    SupportSuccessResponse,
)
from app.dto.admin import (
    AdminMetricsOverviewResponse,
    AdminPilotDocumentItem,
    AdminPilotEmploymentApplicationItem,
    AdminVoiceCallItem,
    AdminVoiceCallEventItem,
    AdminCustomerListItem,
    AdminCustomerStatsResponse,
    AdminDeleteErrandResponse,
    AdminErrandStatusUpdateResponse,
    AdminAssignPilotResponse,
    AdminPilotDispatchStatusResponse,
    AdminPilotDocumentReviewResponse,
    AdminReviewAttachmentResponse,
    AdminCustomersByCountryResponse,
    AdminUnverifiedCustomersResponse,
    AdminPurgeUnverifiedCustomersResponse,
)
from app.dto.system import (
    HealthResponse,
    ReadinessResponse,
    DbHealthResponse,
    AnomalyAlertItem,
    AnalyticsVisitResponse,
)
from app.dto.errand import (
    AttachmentItem,
    ErrandAttachmentItem,
    AttachmentLabelResponse,
    AttachmentShareResponse,
    ErrandMessageItem,
    ErrandMessagesResponse,
)
from app.dto.dashboard import (
    CustomerDashboardStats,
    CustomerActiveErrandItem,
    CustomerRecentErrandItem,
    CustomerSpendingSummary,
    CustomerRecommendedAction,
    CustomerDashboardResponse,
    PilotDashboardStats,
    PilotEarningsSummary,
    PilotAvailabilitySummary,
    PilotAlertItem,
    PilotDashboardResponse,
    UnifiedDashboardResponse,
)

from app.dto.voice import (
    VoiceCallStartResponse,
    VoiceCallbackResponse,
)
